import random

def Any():
    name = random.randint(1,100)
    if name == 1: print('Village name is Kimber')
    if name == 2: print('Village name is Carroway')
    if name == 3: print('Village name is Frozen Head')
    if name == 4: print('Village name is Tatetown')
    if name == 5: print('Village name is Jim Town')
    if name == 6: print('Village name is Big Lick')
    if name == 7: print('Village name is Grassy Cove')
    if name == 8: print('Village name is Midway')
    if name == 9: print('Village name is Ozone')
    if name == 10: print('Village name is Bone Cave')
    if name == 11: print('Village name is Cedar Grove')
    if name == 12: print('Village name is Bon Aire')
    if name == 13: print('Village name is Doyle')
    if name == 14: print('Village name is Ravenscroft')
    if name == 15: print('Village name is Walling')
    if name == 16: print('Village name is Boma')
    if name == 17: print('Village name is Brotherton Mountain')
    if name == 18: print('Village name is Cane Creek')
    if name == 19: print('Village name is Cedar Hill')
    if name == 20: print('Village name is Dry Valley')
    if name == 21: print('Village name is Double Springs')
    if name == 22: print('Village name is Gentry')
    if name == 23: print('Village name is Post Oak')
    if name == 24: print('Village name is Silver Point')
    if name == 25: print('Village name is West Gate')
    if name == 26: print('Village name is Winona')
    if name == 27: print('Village name is Little Crab')
    if name == 28: print('Village name is Pen Mellin')
    if name == 29: print('Village name is Shirley')
    if name == 30: print('Village name is Tinch Town')
    if name == 31: print('Village name is Wilder')
    if name == 32: print('Village name is Zenith')
    if name == 33: print('Village name is Flat Top Mountain')
    if name == 34: print('Village name is Harrison')
    if name == 35: print('Village name is Middle Valley')
    if name == 36: print('Village name is Ooltewah')
    if name == 37: print('Village name is Sale Creek')
    if name == 38: print('Village name is Bakewell')
    if name == 39: print('Village name is George Town')
    if name == 40: print('Village name is Shady Grove')
    if name == 41: print('Village name is Hale Town')
    if name == 42: print('Village name is Winesap')
    if name == 43: print('Village name is Sequatchie')
    if name == 44: print('Village name is Running Water')
    if name == 45: print('Village name is Cordova')
    if name == 46: print('Village name is Eads')
    if name == 47: print('Village name is Ellendale')
    if name == 48: print('Village name is Fishervale')
    if name == 49: print('Village name is Rosemark')
    if name == 50: print('Village name is Beech Grove')
    if name == 51: print('Village name is Bethel')
    if name == 52: print('Village name is Briceville')
    if name == 53: print('Village name is Claxton')
    if name == 54: print('Village name is Fork Mountain')
    if name == 55: print('Village name is Laurel Grove')
    if name == 56: print('Village name is Rosedale')
    if name == 57: print('Village name is Branchville')
    if name == 58: print('Village name is Bugscuffe')
    if name == 59: print("Village name is Cortner's Station")
    if name == 60: print('Village name is Bell Tower')
    if name == 61: print('Village name is Craggie Hope')
    if name == 62: print('Village name is Joelton')
    if name == 63: print('Village name is Shaklett')
    if name == 64: print('Village name is Cold Springs')
    if name == 65: print('Village name is Armona')
    if name == 66: print('Village name is Binfield')
    if name == 67: print('Village name is Clover Hill')
    if name == 68: print('Village name is Kinzel Springs')
    if name == 69: print('Village name is Laws Chapel')
    if name == 70: print('Village name is Mentor')
    if name == 71: print('Village name is Mint')
    if name == 72: print('Village name is Sunshine')
    if name == 73: print('Village name is Meltron')
    if name == 74: print('Village name is Coal Hill')
    if name == 75: print('Village name is Misty Ridge')
    if name == 76: print('Village name is Prospect')
    if name == 77: print('Village name is Tasso')
    if name == 78: print('Village name is Bluewing')
    if name == 79: print('Village name is Brandyville')
    if name == 80: print('Village name is Gassaway')
    if name == 81: print('Village name is Iconium')
    if name == 82: print('Village name is Readyville')
    if name == 83: print('Village name is Sugar Tree Knob')
    if name == 84: print('Village name is Hollow Brock')
    if name == 85: print('Village name is Buema Vista')
    if name == 86: print('Village name is Lvinia')
    if name == 87: print('Village name is Leach')
    if name == 88: print('Village name is Yuma')
    if name == 89: print('Village name is West Port')
    if name == 90: print('Village name is Big Spring')
    if name == 91: print('Village name is Bitter End')
    if name == 92: print('Village name is Stoney Creek')
    if name == 93: print('Village name is Fish Springs')
    if name == 94: print('Village name is Antioch')
    if name == 95: print('Village name is Ovoca')
    if name == 96: print('Village name is Crockett Mills')
    if name == 97: print('Village name is Free Hill')
    if name == 98: print("Village name is Butler's Landing")
    if name == 99: print('Village name is Lilly Dale')
    if name == 100: print('Village name is Raven Hill')
    population = (random.randint(1,10))*100
    print('It has a population of',population,'people')
    wealth = random.randint(1,4)
    if wealth == 1: print('The village is Impoverished. The people of the village have barely enough food to eat. Everything is filthy, and everything stinks. What should be working in this village appears to be broken or worn out. There are very few buildings with a couple small shacks, and no walls. This village is either extremely isolated, or extremely oppressed.')
    if wealth == 2: print("The village is Poor. The people of the village live in poverty, but most seem content in spite of it. The streets are dirty, but the people make do with what they've got. Most of the buildings are small, and a short wall surrounds the village that looks slapped together using random pieces of scrap. This village is either a little isolated, or a little oppressed.")
    if wealth == 3: print("The village is Wealthy. The people of this village seem busy, yet driven. The streets are clean and optimised for productivity. Most of the buildings are spacious, and there is probably a tall, thick, wooden wall that surrounds this village.")
    if wealth == 4: print("The village is Opulent. The people of this village sound jolly and appear well fed. The streets are flashy, featuring wide, stone roads for easy travel. Most of the buildings are artfully done, favouring beauty over practicality. There is probably a strong wall made of stone or brick that surrounds the village, and it borders becoming a town. This village is either heavily trafficked, or heavily sponsored.")
    greettype = random.randint(1,2)
    if greettype == 1:
        verbal = random.randint(1,11)
        if verbal == 1: print("The people of this village greet people by saying, 'Good Morrow!'")
        if verbal == 2: print("The people of this village greet people by saying, 'Hail fellow!'")
        if verbal == 3: print("The people of this village greet people by saying, 'How ya goin?'")
        if verbal == 4: print("The people of this village greet people by saying, 'Howdy-doody?'")
        if verbal == 5: print("The people of this village greet people by saying, 'Salutations!'")
        if verbal == 6: print("The people of this village greet people by saying, 'Top of the mornin' to ya!'")
        if verbal == 7: print("The people of this village greet people by saying, 'Well met!'")
        if verbal == 8: print("The people of this village greet people by saying, 'Wesap hala!'")
        if verbal == 9: print("The people of this village greet people by saying, 'Whadda you at?'")
        if verbal == 10: print("The people of this village greet people by saying, 'What's kickin?'")
        if verbal == 11: print("The people of this village greet people by saying, 'Hello!'")
        if verbal == 12: print("the people of this village greet people by saying, 'Teehee!'")
    else:
        greeting = random.randint(1,11)
        if greeting == 1: print("The people of this village greet people by back patting.")
        if greeting == 2: print("The people of this village greet people by bowing.")
        if greeting == 3: print("The people of this village greet people by butterfly kiss.")
        if greeting == 4: print("The people of this village greet people by cheek kissing.")
        if greeting == 5: print("The people of this village greet people by waving.")
        if greeting == 6: print("The people of this village greet people by fist bumps.")
        if greeting == 7: print("The people of this village greet people by handshakes.")
        if greeting == 8: print("The people of this village greet people by hongi.")
        if greeting == 9: print("The people of this village greet people by salute.")
        if greeting == 10: print("The people of this village greet people by spartan handshake.")
        if greeting == 11: print("The people of this village greet people by clicking heels.")
    holiday = random.randint(1,4)
    if holiday == 1: print("The holiday is to celebrate and be thankful for a successful harvest.")
    if holiday == 2: print("The holiday is to celebrate and remember a historic figure.")
    if holiday == 3: print("The holiday is to celebrate and remember a historic victory.")
    if holiday == 4: print("The holiday is to celebrate and show gratitude for each other.")
    offwork = random.randint(1,2)
    if offwork == 1: print("Nobody works.")
    if offwork == 2: print("Some shops stay open/staffed.")
    noactivities1 = random.randint(2,4)
    noactivities2 = random.randint(2,4)
    totalactivities = (noactivities1+noactivities2)/2
    done = 0
    while totalactivities >= done:
        activity = random.randint(1,(22-done))
        done = done+1
        if activity == 1: print("Activity",done,"is dancing around a bonfire.")
        if activity == 2: print("Activity",done,"is dancing in the streets.")
        if activity == 3: print("Activity",done,"is dressing up in costumes.")
        if activity == 4: print("Activity",done,"is excessive drinking.")
        if activity == 5: print("Activity",done,"is face painting.")
        if activity == 6: print("Activity",done,"is feasting all together oudoors.")
        if activity == 7: print("Activity",done,"is feasting at home with family.")
        if activity == 8: print("Activity",done,"is floating lanterns.")
        if activity == 9: print("Activity",done,"is flying kites.")
        if activity == 10: print("Activity",done,"is giving gifts.")
        if activity == 11: print("Activity",done,"is going on a date.")
        if activity == 12: print("Activity",done,"is lighting firecrackers.")
        if activity == 13: print("Activity",done,"is lighting fireworks.")
        if activity == 14: print("Activity",done,"is playing games together.")
        if activity == 15: print("Activity",done,"is singing all day.")
        if activity == 16: print("Activity",done,"is singing all night.")
        if activity == 17: print("Activity",done,"is telling jokes.")
        if activity == 18: print("Activity",done,"is telling stories.")
        if activity == 19: print("Activity",done,"is throwing coloured powder.")
        if activity == 20: print("Activity",done,"is throwing flower petals.")
        if activity == 22: print("Activity",done,"is a group orgy.")
        if activity == 21: print("Activity",done,"is sacrificing someone.")
    Issue = random.randint(1,30)
    if Issue == 1:
        threat = random.randint(1,13)
        if threat == 1: print('There is currently a drought.')
        if threat == 2: print('An earthquake will happen.')
        if threat == 3: print('A flood will happen.')
        if threat == 4: print('A thunderstorm will happen.')
        if threat == 5: print('A tornado will happen.')
        if threat == 6: print('A volcanic erruption will happen.')
        if threat == 7: print('A wildfire will happen.')
        if threat == 8: print('An earthquake just happen.')
        if threat == 9: print('A flood just happen.')
        if threat == 10: print('A thunderstorm just happen.')
        if threat == 11: print('A tornado just happen.')
        if threat == 12: print('A volcanic erruption just happen.')
        if threat == 13: print('A wildfire just happen.')
    if Issue == 2:
        nest = random.randint(1,8)
        if nest == 1: print('There is a Giand Centipede infestation')
        if nest == 2: print('There is a Giant Rat infestation')
        if nest == 3: print('There is a Giant Wasp infestation')
        if nest == 4: print('There is a Giant Wolf Spider infestation')
        if nest == 5: print('There is a Kobold infestation')
        if nest == 6: print('There is a Poisonous Snake infestation')
        if nest == 7: print('There is a Bat infestation')
        if nest == 8: print('There is an Insect infestation')
    if Issue == 3:
        raider = random.randint(1,16)
        if raider == 1: print('The village is about to be raided by bugbears.')
        if raider == 2: print('The village is about to be raided by drow.')
        if raider == 3: print('The village is about to be raided by duergar.')
        if raider == 4: print('The village is about to be raided by gnolls.')
        if raider == 5: print('The village is about to be raided by goblins.')
        if raider == 6: print('The village is about to be raided by hobgoblins.')
        if raider == 7: print('The village is about to be raided by orcs.')
        if raider == 8: print('The village is about to be raided by rival village.')
        if raider == 9: print('The village has just been raided by bugbears.')
        if raider == 10: print('The village has just been raided by drow.')
        if raider == 11: print('The village has just been raided by duergar.')
        if raider == 12: print('The village has just been raided by gnolls.')
        if raider == 13: print('The village has just been raided by goblins.')
        if raider == 14: print('The village has just been raided by hobgoblins.')
        if raider == 15: print('The village has just been raided by orcs.')
        if raider == 16: print('The village has just been raided by rival village.')
    cryptid = random.randint(1,30)
    if cryptid == 1: print("the villagers believe there is a Bunyip living nearby.")
    if cryptid == 2: print("the villagers believe there is a Chupacabra living nearby.")
    if cryptid == 3: print("the villagers believe there is a Death Worm living nearby.")
    if cryptid == 4: print("the villagers believe there is a Ferus Devil living nearby.")
    if cryptid == 5: print("the villagers believe there is a Nessie living nearby.")
    if cryptid == 6: print("the villagers believe there is a Ogopogo living nearby.")
    if cryptid == 7: print("the villagers believe there is a Slenderman living nearby.")
    if cryptid == 8: print("the villagers believe there is a Thunderbird living nearby.")
    if cryptid == 9: print("the villagers believe there is a Wendigo living nearby.")
    if cryptid == 10: print("the villagers believe there is a Yeti/Bigfoot living nearby.")
    gossip = random.randint(1,12)
    if gossip == 1: print(str('____ had an accident and may never recover.'))
    if gossip == 2: print(str('____ has no children and is losing fertility.'))
    if gossip == 3: print(str('____ is cursed because of a physical defect.'))
    if gossip == 4: print(str('____ is dying from an infectious disease.'))
    if gossip == 5: print(str("____ is broke, and can't support their family."))
    if gossip == 6: print(str('____ is lowering product quality to cut costs.'))
    if gossip == 7: print(str('____ someone is using tax money for their vacations.'))
    if gossip == 8: print(str('____ just inherited a huge sum of money.'))
    if gossip == 9: print(str("____ just had a child, but it isn't theirs/their spouse's."))
    if gossip == 10: print(str('____ is dating two people at the same time.'))
    if gossip == 11: print(str('____ is having an affair with their superiors wife.'))
    if gossip == 12: print(str('____ is no longer living with their spouse.'))
Any()