import pyautogui
import keyboard
import time

#https://www.jetpunk.com/user-quizzes/22274/countries-of-africa-quiz
time.sleep(2)
pyautogui.typewrite("AlgeriaAngolaBeninBotswanaBurkinaFasoBurundiCameroonCapeVerdeCentralAfricanRepublicChadComorosDRCDjiboutiEgyptEquatorialGuineaEritreaEswatiniEthiopiaGabonGambiaGhanaGuineaGuineaBissauIvoryCoastKenyaLesothoLiberiaLibyaMadagascarMalawiMaliMauritaniaMauritiusMoroccoMozambiqueNamibiaNigerNigeriaRep oftheCongoRwandaSenegalSeychellesSierraLeoneSomaliaSouthAfricaSouthSudanSudanSaoTomeTanzaniaTogoTunisiaUgandaZambiaZimbabwe")