import pyautogui
import keyboard
import time

#https://www.jetpunk.com/quizzes/name-the-elements
time.sleep(2)
pyautogui.typewrite("HydrogenHeliumLithiumBerylliumBoronCarbonNitrogenOxygenFluorineNeonSodiumMagnesiumAluminiumSiliconPhosphorusSulfurChlorineArgonPotassiumCalciumScandiumTitaniumVanadiumChromiumManganeseIronCobaltNickelCopperZincGalliumGermaniumArsenicSeleniumBromineKryptonRubidiumStrontiumYttriumZirconiumNiobiumMolybdenumTechnetiumRutheniumRhodiumPalladiumSilverCadmiumIndiumTinAntimonyTelluriumIodineXenonCaesiumBariumLanthanumCeriumPraseodymiumNeodymiumPromethiumSamariumEuropiumGadoliniumTerbiumDysprosiumHolmiumErbiumThuliumYtterbiumLutetiumHafniumTantalumTungstenRheniumOsmiumIridiumPlatinumGoldMercuryThalliumLeadBismuthPoloniumAstatineRadonFranciumRadiumActiniumThoriumProtactiniumUraniumNeptuniumPlutoniumAmericiumCuriumBerkeliumCaliforniumEinsteiniumFermiumMendeleviumNobeliumLawrenciumRutherfordiumDubniumSeaborgiumBohriumHassiumMeitneriumDarmstadtiumRoentgeniumCoperniciumNihoniumFleroviumMoscoviumLivermoriumTennessineOganesson")
