import pyautogui
import keyboard
import time

#https://www.jetpunk.com/quizzes/how-many-states-can-you-name
#https://www.jetpunk.com/quizzes/50-states-one-minute-quiz
time.sleep(2)
pyautogui.typewrite("AlabamaAlaskaArizonaArkansasCaliforniaColoradoConnecticutDelawareFloridaGeorgiaHawaiiIdahoIllinoisIndianaIowaKansasKentuckyLouisianaMaineMarylandMassachusettsMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNewHampshireNewJerseyNewMexicoNewYorkNorthCarolinaNorthDakotaOhioOklahomaOregonPennsylvaniaRhodeIslandSouthCarolinaSouthDakotaTennesseeTexasUtahVermontVirginiaWashingtonWestVirginiaWisconsinWyoming")
